### ISSUE TITLE
Datasets cannot be downloaded

### ISSUE THREAD

**Issue by xiaobaitubaibaibai** [teddykoker/u-noise#1]
I've tried many times, but the web page reminds me of a network error, or the connection is always down

**Comment by teddykoker** [comment]
Hi there! Unfortunately I have no association with the provider of the original data - however I am able to download just fine as long as I am logged into my gmail account - without being logged in I get an error:
>Sorry, you can't view or download this file at this time.
>
>Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator.

I would recommend creating a google account and then trying to download (which worked fine for me just now on multiple devices). 

If this fails I can try to find somewhere to store the data temporarily so you can download.

**Comment by xiaobaitubaibaibai** [comment]
> 你好呀！不幸的是，我与原始数据的提供者没有关联——但是，只要我登录到我的 gmail 帐户，我就可以正常下载——如果没有登录，我会收到一个错误：
> 
> > 抱歉，您目前无法查看或下载此文件。
> > 最近查看或下载此文件的用户过多。请稍后再次尝试访问该文件。如果您尝试访问的文件特别大或与多人共享，则最多可能需要 24 小时才能查看或下载该文件。如果 24 小时后您仍然无法访问文件，请联系您的域管理员。
> 
> 我建议创建一个 google 帐户，然后尝试下载（这对我来说现在在多个设备上运行良好）。
> 
> 如果失败，我可以尝试找个地方暂时存储数据，以便您可以下载。

thank you very much
