### ISSUE TITLE
Citations in the paper

### ISSUE THREAD

**Issue by kiraving** [teddykoker/u-noise#4]
Dear Teddy Koker @teddykoker and co-authors,

I would like to kindly ask you to revise the citations and update the arxiv version of your paper.

1) [6] Vinogradova, K., Dibrov, A., & Myers, G. (2020). Towards Interpretable Semantic Segmentation via Gradient-Weighted Class Activation Mapping (Student Abstract). Proceedings of the AAAI Conference on Artificial Intelligence, 34(10), 13943-13944. https://doi.org/10.1609/aaai.v34i10.7244

2) They either return explanations for a part of the image [6, 7] or for a single pixel [6] or for the whole class [6]. 
In :
"There are only a few previous works that focus on segmentation interpretability [6, 7]. These works solve the problem in
a lower resolution setup, and then up-sample to get pixel level explanation. They also only return explanations with respect
to a single pixel [ 6] or a part of the image [7]. "

3) "Finally, for Grad-CAM, we follow [ 6, 11 ] and obtain a heatmap with respect to the convolutional layer at the bottleneck of the Utility model."

Seg-Grad-CAM, the method proposed in my peer-reviewed publication, takes the gradients with respect to the convolutional layer at the bottleneck of the U-Net and produces explanations for a) single pixel, b) class mask (all pixels belonging to the class), c) ROI (e.g. an instance).

I would really appreciate it and cite your paper in my current work.

Kind regards,
Kira

**Comment by teddykoker** [comment]
Hi Kira,

Thank you for reaching out; we appreciate the corrections. I have updated the citation and revised the text as suggested. I have updated the paper (preview [here](https://github.com/teddykoker/u-noise/files/10094534/revision.pdf)) on arxiv, and it should appear `Mon, 28 Nov 2022 01:00:00 GMT`. Best of luck with your current work, I look forward to reading it!

Best,
Teddy

**Comment by kiraving** [comment]
Hi Teddy,
Thank you so much for the rapid update!
